plugins {
    id 'java'
    id("io.qameta.allure") version "4.1.0"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    implementation platform('org.junit:junit-bom:5.14.0')
    implementation 'org.junit.jupiter:junit-jupiter'

    implementation(platform("io.qameta.allure:allure-bom:2.35.4"))

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'

    // Selenide
    testImplementation 'com.codeborne:selenide:7.0.0'
    testImplementation 'com.codeborne:selenide-proxy:7.0.0'
    testImplementation 'com.codeborne:selenide-core:7.0.0'

    // Генератор случайных данных Datafaker
    implementation 'net.datafaker:datafaker:2.5.4'

    // Библиотека для генерации ASCII-арта JFiglet
    implementation 'com.github.lalyos:jfiglet:0.0.8'

    // Allure
    testImplementation 'io.qameta.allure:allure-junit5:2.35.4'
    testImplementation 'io.qameta.allure:allure-assertj:2.35.4'
    testImplementation 'io.qameta.allure:allure-java-commons:2.35.4'
    testImplementation'io.qameta.allure:allure-rest-assured:2.35.4'
    testImplementation 'io.qameta.allure:allure-selenide:2.35.4'

    testImplementation 'org.aspectj:aspectjweaver:1.9.25.1'

    //Библиотеки Кукумбера
    testImplementation "io.cucumber:cucumber-java:7.18.0"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:7.18.0"

    //Библиотеки JUnit
    testImplementation "org.junit.platform:junit-platform-suite:1.10.3"
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.3"

    // Source: https://mvnrepository.com/artifact/io.rest-assured/rest-assured
    testImplementation 'io.rest-assured:rest-assured:5.5.6'

    // Source: https://mvnrepository.com/artifact/org.hamcrest/hamcrest
    testImplementation 'org.hamcrest:hamcrest:3.0'

    // JAX-B dependencies for JDK 9+
    implementation "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2"
    implementation "org.glassfish.jaxb:jaxb-runtime:2.3.2"

    // Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind
    implementation 'tools.jackson.core:jackson-databind:3.2.1'
}

allure {
    //version = "3.9.0"   // Allure 3 (default)
     version = "2.42.1"  // Allure 2
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}